mod dry_run_falls_back_to_normal_issue_when_retained_retry_loses_ownership;
mod dry_run_returns_none_when_intake_has_no_service_owned_candidate;
mod format_run_once_summary_surfaces_continuation_boundaries;
mod no_eligible_issue_message_includes_operator_hint;
mod targeted_identifier_dispatch_rejects_different_status_visible_closeout_lane;
mod targeted_identifier_dispatch_rejects_different_status_visible_review_repair_lane;
