mod status;
mod status_support;

#[allow(unused_imports)]
pub(super) use crate::{
	agent::{MODEL_EXECUTION_IDLE_TIMEOUT, RUN_LEASE_IDLE_TIMEOUT},
	config::{ReviewLevel, ServiceConfig},
	loop_contract::DecisionContract,
	orchestrator::{
		self, AgentEvidenceSource, AgentPrivateEvidenceRef, AuthorityBoundaryChangedSurface,
		AuthorityBoundaryCheckInput, AuthorityBoundaryDisposition, AuthorityBoundaryPolicyDecision,
		AuthorityBoundarySurface, AuthorityDecisionRequestInput, ControlPlaneProjectTick,
		DASHBOARD_MAX_WEBSOCKET_CLIENTS, DashboardClientSubscription, DashboardEventHub,
		EvidenceRequest, OperatorCodexAccountControlStatus, OperatorControlRequests,
		OperatorExecutionProgramNodeStatus, OperatorExecutionProgramStatus,
		OperatorGitHubCliAuthority, OperatorPostReviewLaneStatus, OperatorProjectStatus,
		OperatorQueuedIssueStatus, OperatorRunStatus, OperatorStatusSnapshot,
		PHASE_GOAL_RECOVERY_EVENT_TYPE, PublishedOperatorSnapshot, RecoveredRuntimeState,
		TERMINAL_GUARDED_RUN_STATUS, TRACKER_RATE_LIMIT_WARNING, TRACKER_TRANSIENT_TIMEOUT_WARNING,
		VALIDATION_EVIDENCE_EVENT_TYPE,
		tests::{
			FakePullRequestReviewStateInspector, FakeTracker,
			TEST_EXTERNAL_REVIEW_AUTO_MERGE_ENABLED_AT, TEST_EXTERNAL_REVIEW_REQUEST_COMMENT_ID,
			TEST_EXTERNAL_REVIEW_REQUEST_CREATED_AT, TEST_NON_EXTERNAL_REVIEW_ACTOR_LOGIN,
			TEST_PROJECT_CONFIG_FILE, TEST_SERVICE_ID, add_external_review_ack,
			add_external_review_findings, add_external_review_pass,
			add_external_review_pass_from_actor, add_external_review_summary, add_origin_remote,
			add_review_request_ack_from_actor, add_review_summary_from_actor, checkout_new_branch,
			commit_worktree_change, git_output, git_remote_url, git_status_success,
			install_fake_admin_merge_gh_response,
			install_fake_admin_merge_gh_response_with_merge_exit_code,
			install_fake_post_issue_comment_gh_response, load_service_config,
			persisted_review_lifecycle_handoff_fixture,
			persisted_review_lifecycle_transition_fixture,
			persisted_review_lifecycle_transition_fixture_for_path,
			profile_scoped_workflow_markdown, rewrite_run_activity_marker_host_boot_id,
			rewrite_run_activity_marker_process_start_identity, sample_blocker, sample_issue,
			sample_issue_with_project_slug_and_sort_fields, sample_issue_with_sort_fields,
			sample_issue_without_needs_attention_team_label, sample_pull_request_review_state,
			sample_pull_request_review_state_page, sample_pull_request_review_state_repository,
			sample_pull_request_review_state_with_pending_requests,
			sample_review_lifecycle_handoff_fixture, sample_review_lifecycle_transition_fixture,
			sample_service_config_toml, sample_service_config_toml_with_github_command_path,
			sample_workflow, sample_workflow_markdown, seed_review_lifecycle_handoff_fixture,
			seed_review_lifecycle_handoff_fixture_for_path,
			seed_review_lifecycle_handoff_fixture_value, seed_review_lifecycle_transition_fixture,
			seed_review_lifecycle_transition_fixture_for_path, service_config_dir,
			service_config_path, service_config_toml_for_config,
			service_config_toml_for_config_with_github_command_path,
			service_config_with_github_token_env_var,
			service_config_with_github_token_env_var_and_command_path,
			service_config_with_review_level, service_workflow_path, temp_project_layout,
			temp_project_layout_with_max_turns, temp_project_layout_with_read_first,
			temp_project_layout_with_tracker_project_slug,
			temp_project_layout_with_tracker_project_slug_and_read_first,
			temp_project_layout_with_tracker_project_slug_max_turns_and_read_first,
			temp_project_layout_with_workflow_markdown, try_git_local_config_value,
			worktree_mapping_for_path, write_service_config,
		},
	},
	prelude::eyre,
	runtime,
	state::{
		self, ChildAgentActivitySummary, CodexAccountActivitySummary, CodexAccountMarker,
		EffectiveRuntimeMarker, ProjectRegistration, ProtocolActivityEventSummary,
		ProtocolActivityMarker, ProtocolActivitySummary, RUN_ACTIVITY_MARKER_FILE,
		RUN_CONTROL_CHANNEL_DIR, RUN_CONTROL_CHANNEL_TRANSPORT_LOCAL_FILE, RUN_OPERATION_AGENT_RUN,
		RUN_OPERATION_GIT_CREDENTIALS, RUN_OPERATION_RECONCILIATION, ReviewLifecycleHandoffFixture,
		ReviewLifecycleTransitionFixture, ReviewPolicyCheckpointInput, StateStore, WorktreeMapping,
	},
	test_support::TestEnvVarGuard,
	tracker::{
		self, IssueTracker, TrackerComment, TrackerIssue, TrackerIssueBlocker, TrackerLabel,
		TrackerState, TrackerTeam, linear::LinearClient, records,
		records::LinearExecutionEventIdentity,
	},
	workflow::WorkflowDocument,
	worktree::{WorktreeManager, WorktreeSpec},
};
pub(super) use rusqlite::Connection;
pub(super) use serde_json::Value;
pub(super) use std::{
	collections::HashMap,
	env, fs,
	io::{ErrorKind, Read, Write},
	net::{Shutdown, SocketAddr, TcpListener, TcpStream},
	path::{Path, PathBuf},
	process::{self, Child, Command},
	sync::{Arc, Mutex},
	thread,
	time::{Duration, Instant},
};
pub(super) use tempfile::TempDir;
pub(super) use time::OffsetDateTime;

use std::{panic, slice};
