mod daemon_planned_closeout_allocates_retry_after_recorded_closeout_failure;
mod daemon_planned_closeout_reuses_handoff_identity_after_parent_failed_status;
mod preserves_handoff_identity_after_recovery;
mod reuses_completed_handoff_identity;
