mod loop_guardrail_does_not_classify_committed_branch_delta_as_no_effective_diff;
mod loop_guardrail_requires_human_when_boundary_evidence_is_missing;
mod loop_guardrail_stops_no_effective_diff_for_retryable_errors_without_delta;
mod loop_guardrail_stops_validation_repeat_when_validation_text_changes;
