use crate::orchestrator::tests::review_landing_orchestration::landing_fallbacks;

#[test]
fn reconcile_post_review_orchestration_skips_runtime_standard_review_while_landing_gates_pending() {
	landing_fallbacks::assert_reconcile_post_review_orchestration_skips_runtime_standard_review_while_landing_gates_pending();
}
