use crate::orchestrator::tests::review_landing_orchestration::landing_fallbacks;

#[test]
fn reconcile_post_review_orchestration_routes_unknown_runtime_standard_review_status_to_attention()
{
	landing_fallbacks::assert_reconcile_post_review_orchestration_routes_unknown_runtime_standard_review_status_to_attention();
}
