use crate::orchestrator::tests::review_landing_orchestration::landing_fallbacks;

#[test]
fn reconcile_post_review_orchestration_escalates_runtime_standard_review_checkpoint_failure_after_budget()
 {
	landing_fallbacks::assert_reconcile_post_review_orchestration_escalates_runtime_standard_review_checkpoint_failure_after_budget();
}
