[package]
authors.workspace    = true
description          = "Decodex vNext service composition root."
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "decodexd"
repository.workspace = true
version.workspace    = true

[dependencies]
clap             = { workspace = true }
decodex-protocol = { workspace = true }
decodex-runtime  = { workspace = true }
serde_json       = { workspace = true }
tokio            = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dev-dependencies]
libc = { workspace = true }
