pub(super) const SCRIPT_PARTS: &[&str] = &[
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity/history.js"
	)),
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity/child-agent/context.js"
	)),
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity/child-agent/buckets.js"
	)),
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity/child-agent/lifecycle.js"
	)),
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity/child-agent.js"
	)),
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity/child-agent/summary.js"
	)),
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity.js"
	)),
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity/notices.js"
	)),
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity/notices/readiness.js"
	)),
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity/notices/list.js"
	)),
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity/notices/accounts.js"
	)),
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity/notices/warnings.js"
	)),
	include_str!(concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/src/orchestrator/operator_dashboard/app/activity/notices/render.js"
	)),
];
