mod exited_child_reconciliation_detects_retained_partial_progress_from_dirty_worktree;
mod exited_child_reconciliation_detects_stalled_failed_runs_from_protocol_idle;
mod exited_child_reconciliation_ignores_superseded_failed_run;
