mod streamable_http_allows_configured_origin;
mod streamable_http_allows_cors_preflight_for_trusted_origin;
mod streamable_http_bearer_auth_accepts_valid_authorization;
mod streamable_http_bearer_auth_challenges_missing_or_invalid_authorization;
mod streamable_http_bind_guard_requires_loopback_or_allowed_origin;
mod streamable_http_elevated_profile_requires_bearer_authorization;
mod streamable_http_rejects_disallowed_origin;
