mod ensure_cli_repo_context_rejects_foreign_config_repo_root;
mod manual_land_closeout_receipt_rejects_mismatched_receipts;
mod manual_land_closeout_receipt_roundtrips;
mod manual_land_handoff_lookup_prefers_current_branch_record;
mod resolve_manual_config_path_uses_registered_project_for_linked_worktree;
