use std::{
	collections::{BTreeMap, BTreeSet},
	fs::File,
	io::Read as _,
	path::Path,
};

use serde::Deserialize;
use serde_json::{Map, Value};
use sha2::{Digest as _, Sha256};

/// Accepted XY-1262 schema receipt used by the marker golden.
pub const ACCEPTED_SCHEMA_RECEIPT: &str = "decodex/vnext-codex-schema-receipt/1";
/// Request methods required by the accepted schema receipt.
pub const REQUIRED_REQUEST_METHODS: &[&str] = &[
	"initialize",
	"account/read",
	"thread/start",
	"thread/list",
	"thread/search",
	"thread/read",
	"thread/resume",
	"thread/name/set",
	"turn/start",
	"account/rateLimits/read",
	"collaborationMode/list",
];
/// Notification methods required by the accepted schema receipt.
pub const REQUIRED_NOTIFICATION_METHODS: &[&str] =
	&["thread/started", "turn/started", "item/started", "item/completed", "turn/completed"];

const COLLABORATION_MARKERS: &[&str] =
	&["collabAgentToolCall", "parentThreadId", "agentNickname", "agentRole", "subAgentActivity"];
const MAX_SCHEMA_FILE_BYTES: u64 = 16 * 1_024 * 1_024;
const ACCEPTED_DIGESTS: &[(&str, &str)] = &[
	("ClientRequest.json", "3f82e5aec5be786c40d21440dfb6d0667d194d872bfa7041bd81c39b4ba56dc3"),
	("ServerNotification.json", "16ce6adadf33aa182f98840c5d33f6294c3c37b2866bb05545c24e0dbf2cc2d2"),
	(
		"codex_app_server_protocol.v2.schemas.json",
		"f5e8d20f3a8f9bb5e5b23ab0c5aa6bde7b12e7e0713606c5d0132651a4959d37",
	),
];

/// One checked-in schema marker set, never a capability promise.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SchemaMarker {
	/// Receipt schema identifier.
	receipt: String,
	/// Exact request method markers.
	request_methods: BTreeSet<String>,
	/// Exact notification method markers.
	notification_methods: BTreeSet<String>,
	/// Collaboration field markers from `ThreadReadResponse`.
	collaboration_markers: BTreeSet<String>,
	/// Canonical hashes recorded by the accepted XY-1262 receipt.
	canonical_sha256: BTreeMap<String, String>,
}
impl SchemaMarker {
	/// Load the accepted checked-in marker golden.
	pub fn accepted() -> Self {
		#[derive(Deserialize)]
		#[serde(deny_unknown_fields)]
		struct SchemaMarkerWire {
			receipt: String,
			request_methods: BTreeSet<String>,
			notification_methods: BTreeSet<String>,
			collaboration_markers: BTreeSet<String>,
			canonical_sha256: BTreeMap<String, String>,
		}

		let marker: SchemaMarkerWire =
			serde_json::from_str(include_str!("../schema/xy-1262-markers.json"))
				.expect("checked-in schema marker golden must be valid");

		Self {
			receipt: marker.receipt,
			request_methods: marker.request_methods,
			notification_methods: marker.notification_methods,
			collaboration_markers: marker.collaboration_markers,
			canonical_sha256: marker.canonical_sha256,
		}
	}

	pub(crate) fn canonical_digests(&self) -> &BTreeMap<String, String> {
		&self.canonical_sha256
	}

	#[cfg(test)]
	pub(crate) fn remove_request_method(&mut self, method: &str) {
		self.request_methods.remove(method);
	}
}

/// Validated generated-schema evidence.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SchemaContract {
	thread_archive: bool,
}
impl SchemaContract {
	/// Validate all required markers before any process or side effect is started.
	pub fn validate(marker: SchemaMarker) -> Result<Self, Vec<String>> {
		let mut missing = Vec::new();

		if marker.receipt != ACCEPTED_SCHEMA_RECEIPT {
			missing.push(format!("receipt:{ACCEPTED_SCHEMA_RECEIPT}"));
		}

		for method in REQUIRED_REQUEST_METHODS {
			if !marker.request_methods.contains(*method) {
				missing.push(format!("request:{method}"));
			}
		}
		for method in REQUIRED_NOTIFICATION_METHODS {
			if !marker.notification_methods.contains(*method) {
				missing.push(format!("notification:{method}"));
			}
		}
		for field in COLLABORATION_MARKERS {
			if !marker.collaboration_markers.contains(*field) {
				missing.push(format!("collaboration:{field}"));
			}
		}
		for (file, digest) in ACCEPTED_DIGESTS {
			if marker.canonical_sha256.get(*file).map(String::as_str) != Some(*digest) {
				missing.push(format!("digest:{file}"));
			}
		}

		if missing.is_empty() {
			Ok(Self { thread_archive: marker.request_methods.contains("thread/archive") })
		} else {
			Err(missing)
		}
	}

	/// Return whether the schema advertises an exact request method.
	pub fn advertises_request(&self, method: &str) -> bool {
		REQUIRED_REQUEST_METHODS.contains(&method)
			|| (method == "thread/archive" && self.thread_archive)
	}

	/// Return whether an accepted collaboration marker is present.
	pub fn advertises_collaboration(&self) -> bool {
		true
	}
}

/// Evidence derived from schema files generated by the exact executable being probed.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct GeneratedSchemaEvidence {
	pub fingerprint: String,
	contract: SchemaContract,
}
impl GeneratedSchemaEvidence {
	pub fn load(
		directory: &Path,
		expected_digests: Option<&BTreeMap<String, String>>,
	) -> Result<Self, Vec<String>> {
		let request = read_json(directory.join("ClientRequest.json"))?;
		let notification = read_json(directory.join("ServerNotification.json"))?;
		let aggregate_path = directory.join("codex_app_server_protocol.v2.schemas.json");
		let aggregate = read_json(&aggregate_path)?;
		let collaboration = read_json(directory.join("v2/ThreadReadResponse.json"))?;
		let request_methods = extract_methods(&request)?;
		let notification_methods = extract_methods(&notification)?;

		validate_collaboration_schema(&collaboration)?;

		let actual_digests = [
			("ClientRequest.json", &request),
			("ServerNotification.json", &notification),
			("codex_app_server_protocol.v2.schemas.json", &aggregate),
		]
		.into_iter()
		.map(|(name, value)| (name.to_owned(), canonical_digest(value)))
		.collect::<BTreeMap<_, _>>();

		if let Some(expected) = expected_digests {
			let mismatches = expected
				.iter()
				.filter(|(name, digest)| actual_digests.get(*name) != Some(*digest))
				.map(|(name, _)| format!("digest:{name}"))
				.collect::<Vec<_>>();

			if !mismatches.is_empty() {
				return Err(mismatches);
			}
		}

		let marker = SchemaMarker {
			receipt: ACCEPTED_SCHEMA_RECEIPT.into(),
			request_methods,
			notification_methods,
			collaboration_markers: COLLABORATION_MARKERS
				.iter()
				.map(|value| (*value).into())
				.collect(),
			canonical_sha256: ACCEPTED_DIGESTS
				.iter()
				.map(|(name, hash)| ((*name).into(), (*hash).into()))
				.collect(),
		};
		let contract = SchemaContract::validate(marker)?;
		let fingerprint = actual_digests
			.get("codex_app_server_protocol.v2.schemas.json")
			.expect("aggregate digest was inserted")
			.clone();

		Ok(Self { fingerprint, contract })
	}

	pub fn contract(&self) -> &SchemaContract {
		&self.contract
	}
}

#[derive(Clone, Copy)]
enum PropertyShape {
	String,
	StringArray,
	Reference(&'static str),
	ReferenceMap(&'static str),
}

pub(crate) fn hex_digest(bytes: &[u8]) -> String {
	bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn extract_methods(value: &Value) -> Result<BTreeSet<String>, Vec<String>> {
	let variants =
		value.get("oneOf").and_then(Value::as_array).ok_or_else(|| vec!["schema:oneOf".into()])?;
	let methods = variants
		.iter()
		.filter_map(|variant| variant.get("properties")?.get("method")?.get("enum")?.as_array())
		.flatten()
		.filter_map(Value::as_str)
		.map(str::to_owned)
		.collect::<BTreeSet<_>>();

	if methods.is_empty() { Err(vec!["schema:method-enum".into()]) } else { Ok(methods) }
}

fn canonical_digest(value: &Value) -> String {
	let bytes = serde_json::to_vec(value).expect("parsed JSON must serialize");

	hex_digest(Sha256::digest(bytes).as_ref())
}

fn read_json(path: impl AsRef<Path>) -> Result<Value, Vec<String>> {
	let path = path.as_ref();
	let file = File::open(path).map_err(|_| vec!["schema:document".into()])?;
	let size = file.metadata().map_err(|_| vec!["schema:document".into()])?.len();

	if size > MAX_SCHEMA_FILE_BYTES {
		return Err(vec!["schema:document-limit".into()]);
	}

	let mut bytes = Vec::with_capacity(usize::try_from(size).unwrap_or(0));

	file.take(MAX_SCHEMA_FILE_BYTES + 1)
		.read_to_end(&mut bytes)
		.map_err(|_| vec!["schema:document".into()])?;

	if bytes.len() as u64 > MAX_SCHEMA_FILE_BYTES {
		return Err(vec!["schema:document-limit".into()]);
	}

	serde_json::from_slice(&bytes).map_err(|_| vec!["schema:document".into()])
}

fn validate_collaboration_schema(value: &Value) -> Result<(), Vec<String>> {
	let definitions = value
		.get("definitions")
		.and_then(Value::as_object)
		.ok_or_else(|| vec!["collaboration:definitions".into()])?;
	let thread = definitions.get("Thread").ok_or_else(|| vec!["collaboration:Thread".into()])?;
	let thread_properties = properties(thread, "Thread")?;

	for field in ["parentThreadId", "agentNickname", "agentRole"] {
		let schema = thread_properties
			.get(field)
			.ok_or_else(|| vec![format!("collaboration:Thread.{field}")])?;

		if !allows_string_or_null(schema) {
			return Err(vec![format!("collaboration:Thread.{field}:type")]);
		}
	}

	let variants = definitions
		.get("ThreadItem")
		.and_then(|schema| schema.get("oneOf"))
		.and_then(Value::as_array)
		.ok_or_else(|| vec!["collaboration:ThreadItem.oneOf".into()])?;

	validate_string_enum(
		definitions,
		"CollabAgentTool",
		&["spawnAgent", "sendInput", "resumeAgent", "wait", "closeAgent"],
	)?;
	validate_string_enum(
		definitions,
		"CollabAgentToolCallStatus",
		&["inProgress", "completed", "failed"],
	)?;
	validate_string_enum(
		definitions,
		"SubAgentActivityKind",
		&["started", "interacted", "interrupted"],
	)?;

	if !definitions.contains_key("CollabAgentState") {
		return Err(vec!["collaboration:CollabAgentState".into()]);
	}

	validate_item_variant(
		variants,
		"collabAgentToolCall",
		&["agentsStates", "id", "receiverThreadIds", "senderThreadId", "status", "tool", "type"],
		&[
			("agentsStates", PropertyShape::ReferenceMap("CollabAgentState")),
			("id", PropertyShape::String),
			("receiverThreadIds", PropertyShape::StringArray),
			("senderThreadId", PropertyShape::String),
			("status", PropertyShape::Reference("CollabAgentToolCallStatus")),
			("tool", PropertyShape::Reference("CollabAgentTool")),
		],
	)?;
	validate_item_variant(
		variants,
		"subAgentActivity",
		&["agentPath", "agentThreadId", "id", "kind", "type"],
		&[
			("agentPath", PropertyShape::String),
			("agentThreadId", PropertyShape::String),
			("id", PropertyShape::String),
			("kind", PropertyShape::Reference("SubAgentActivityKind")),
		],
	)?;

	Ok(())
}

fn validate_string_enum(
	definitions: &Map<String, Value>,
	name: &str,
	required: &[&str],
) -> Result<(), Vec<String>> {
	let values = definitions
		.get(name)
		.and_then(|schema| schema.get("enum"))
		.and_then(Value::as_array)
		.ok_or_else(|| vec![format!("collaboration:{name}:enum")])?;

	if definitions.get(name).and_then(|schema| schema.get("type")).and_then(Value::as_str)
		!= Some("string")
		|| required
			.iter()
			.any(|required| !values.iter().any(|value| value.as_str() == Some(required)))
	{
		return Err(vec![format!("collaboration:{name}:enum")]);
	}

	Ok(())
}

fn validate_item_variant(
	variants: &[Value],
	kind: &str,
	required_fields: &[&str],
	property_shapes: &[(&str, PropertyShape)],
) -> Result<(), Vec<String>> {
	let variant = variants
		.iter()
		.find(|variant| {
			variant
				.get("properties")
				.and_then(|properties| properties.get("type"))
				.and_then(|schema| schema.get("enum"))
				.and_then(Value::as_array)
				.is_some_and(|values| values.as_slice() == [Value::String(kind.into())])
		})
		.ok_or_else(|| vec![format!("collaboration:ThreadItem.{kind}")])?;

	if variant.get("type").and_then(Value::as_str) != Some("object") {
		return Err(vec![format!("collaboration:ThreadItem.{kind}:type")]);
	}

	let required = variant
		.get("required")
		.and_then(Value::as_array)
		.ok_or_else(|| vec![format!("collaboration:ThreadItem.{kind}:required")])?;

	for field in required_fields {
		if !required.iter().any(|value| value.as_str() == Some(field)) {
			return Err(vec![format!("collaboration:ThreadItem.{kind}:required:{field}")]);
		}
	}

	let properties = properties(variant, kind)?;

	for (field, shape) in property_shapes {
		let schema = properties
			.get(*field)
			.ok_or_else(|| vec![format!("collaboration:ThreadItem.{kind}.{field}")])?;
		let valid = match shape {
			PropertyShape::String => schema.get("type").and_then(Value::as_str) == Some("string"),
			PropertyShape::StringArray =>
				schema.get("type").and_then(Value::as_str) == Some("array")
					&& schema
						.get("items")
						.and_then(|items| items.get("type"))
						.and_then(Value::as_str)
						== Some("string"),
			PropertyShape::Reference(name) => references(schema, name),
			PropertyShape::ReferenceMap(name) =>
				schema.get("type").and_then(Value::as_str) == Some("object")
					&& schema
						.get("additionalProperties")
						.is_some_and(|value| references(value, name)),
		};

		if !valid {
			return Err(vec![format!("collaboration:ThreadItem.{kind}.{field}:type")]);
		}
	}

	Ok(())
}

fn properties<'a>(value: &'a Value, owner: &str) -> Result<&'a Map<String, Value>, Vec<String>> {
	value
		.get("properties")
		.and_then(Value::as_object)
		.ok_or_else(|| vec![format!("collaboration:{owner}:properties")])
}

fn allows_string_or_null(value: &Value) -> bool {
	value.get("type").and_then(Value::as_array).is_some_and(|types| {
		types.len() == 2
			&& types.iter().any(|value| value.as_str() == Some("string"))
			&& types.iter().any(|value| value.as_str() == Some("null"))
	})
}

fn references(value: &Value, name: &str) -> bool {
	let expected = format!("#/definitions/{name}");

	value.get("$ref").and_then(Value::as_str) == Some(expected.as_str())
		|| ["allOf", "anyOf", "oneOf"].iter().any(|key| {
			value
				.get(key)
				.and_then(Value::as_array)
				.is_some_and(|values| values.iter().any(|value| references(value, name)))
		})
}

#[cfg(test)]
mod tests {
	use crate::schema::{REQUIRED_REQUEST_METHODS, SchemaContract, SchemaMarker};

	#[test]
	fn accepted_marker_golden_satisfies_the_xy_1262_contract() {
		let marker = SchemaMarker::accepted();
		let contract = SchemaContract::validate(marker).unwrap();

		for method in REQUIRED_REQUEST_METHODS {
			assert!(contract.advertises_request(method));
		}
		for method in ["thread/archive", "thread/search"] {
			assert!(contract.advertises_request(method));
		}

		assert!(contract.advertises_collaboration());
	}

	#[test]
	fn marker_validation_reports_exact_missing_contract_members() {
		let mut marker = SchemaMarker::accepted();

		marker.notification_methods.remove("turn/completed");
		marker.collaboration_markers.remove("parentThreadId");

		let missing = SchemaContract::validate(marker).unwrap_err();

		assert_eq!(missing, ["notification:turn/completed", "collaboration:parentThreadId"]);
	}

	#[test]
	fn marker_validation_rejects_a_tampered_receipt_digest() {
		let mut marker = SchemaMarker::accepted();

		marker.canonical_sha256.insert("ClientRequest.json".into(), "wrong".into());

		assert_eq!(SchemaContract::validate(marker).unwrap_err(), ["digest:ClientRequest.json"]);
	}

	#[test]
	fn canonical_digest_ignores_json_object_order() {
		let first: serde_json::Value = serde_json::from_str(r#"{"b":2,"a":1}"#).unwrap();
		let second: serde_json::Value = serde_json::from_str(r#"{"a":1,"b":2}"#).unwrap();

		assert_eq!(super::canonical_digest(&first), super::canonical_digest(&second));
	}

	#[test]
	fn collaboration_markers_in_descriptions_or_unrelated_tokens_are_rejected() {
		let false_schema = serde_json::json!({
			"description": "collabAgentToolCall parentThreadId agentNickname agentRole subAgentActivity",
			"definitions": {
				"Thread": {"properties": {"unrelated": {"enum": ["parentThreadId", "agentNickname", "agentRole"]}}},
				"ThreadItem": {"oneOf": [{"description": "collabAgentToolCall subAgentActivity"}]}
			}
		});

		assert!(super::validate_collaboration_schema(&false_schema).is_err());
	}

	#[test]
	fn collaboration_variants_require_expected_fields_and_shapes() {
		let mut schema = structurally_valid_collaboration_schema();

		schema["definitions"]["ThreadItem"]["oneOf"][0]["properties"]["receiverThreadIds"]["items"]
			["type"] = serde_json::json!("number");

		assert_eq!(
			super::validate_collaboration_schema(&schema).unwrap_err(),
			["collaboration:ThreadItem.collabAgentToolCall.receiverThreadIds:type"]
		);
	}

	fn structurally_valid_collaboration_schema() -> serde_json::Value {
		serde_json::json!({
			"definitions": {
				"CollabAgentState": {"type": "object"},
				"CollabAgentTool": {"type": "string", "enum": ["spawnAgent", "sendInput", "resumeAgent", "wait", "closeAgent"]},
				"CollabAgentToolCallStatus": {"type": "string", "enum": ["inProgress", "completed", "failed"]},
				"SubAgentActivityKind": {"type": "string", "enum": ["started", "interacted", "interrupted"]},
				"Thread": {"properties": {
					"parentThreadId": {"type": ["string", "null"]},
					"agentNickname": {"type": ["string", "null"]},
					"agentRole": {"type": ["string", "null"]}
				}},
				"ThreadItem": {"oneOf": [
					{
						"type": "object",
						"required": ["agentsStates", "id", "receiverThreadIds", "senderThreadId", "status", "tool", "type"],
						"properties": {
							"agentsStates": {"type": "object", "additionalProperties": {"$ref": "#/definitions/CollabAgentState"}},
							"id": {"type": "string"},
							"receiverThreadIds": {"type": "array", "items": {"type": "string"}},
							"senderThreadId": {"type": "string"},
							"status": {"allOf": [{"$ref": "#/definitions/CollabAgentToolCallStatus"}]},
							"tool": {"allOf": [{"$ref": "#/definitions/CollabAgentTool"}]},
							"type": {"enum": ["collabAgentToolCall"]}
						}
					},
					{
						"type": "object",
						"required": ["agentPath", "agentThreadId", "id", "kind", "type"],
						"properties": {
							"agentPath": {"type": "string"},
							"agentThreadId": {"type": "string"},
							"id": {"type": "string"},
							"kind": {"$ref": "#/definitions/SubAgentActivityKind"},
							"type": {"enum": ["subAgentActivity"]}
						}
					}
				]}
			}
		})
	}
}
