mod cleared_checkpoint_allows_cross_attempt_phase_goal_inheritance;
mod cleared_checkpoint_allows_same_run_phase_goal_recovery_candidate;
mod retry_phase_goal_resumes_cross_attempt_handoff_after_recovered_validation_pass;
