mod rebind_validation_completes_current_existing_authority_failure_state_drift;
mod rebind_validation_completes_current_existing_authority_state_transition;
mod rebind_validation_refreshes_existing_same_branch_pr_authority;
mod rebind_validation_rejects_current_existing_authority_as_noop;
mod rebind_validation_rejects_stale_authority_failure_state_drift_recovery;
