mod dirty_runtime_failures_record_retained_progress_instead_of_terminal_failure;
mod explicit_manual_attention_keeps_manual_terminal_path_with_dirty_worktree;
mod manual_attention_failure_overrides_succeeded_run_status;
mod prepare_issue_run_clears_terminal_guard_marker_when_new_attempt_starts;
mod retryable_failures_ignore_prior_continuation_attempts_in_writeback;
