[package]
authors.workspace    = true
description          = "PostgreSQL product-state adapter boundary for Decodex vNext."
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "decodex-postgres"
repository.workspace = true
version.workspace    = true

[dependencies]
deadpool-postgres = "=0.14.1"
decodex-core      = { workspace = true }
libc              = { workspace = true }
refinery          = { version = "=0.9.2", default-features = false, features = ["tokio-postgres"] }
regex             = { workspace = true }
serde_json        = { workspace = true }
sha2              = { workspace = true }
time              = { workspace = true, features = ["parsing"] }
tokio             = { workspace = true }
tokio-postgres    = { workspace = true, features = ["with-serde_json-1"] }
