mod issue;
mod mutation;
mod team;

pub(super) use self::{
	issue::{
		ISSUE_BLOCKERS_QUERY, ISSUE_BY_IDENTIFIER_QUERY, ISSUE_COMMENTS_QUERY,
		ISSUE_INVERSE_RELATIONS_QUERY, ISSUE_RELATIONS_QUERY, ISSUES_BY_IDS_QUERY,
		ISSUES_WITH_LABEL_QUERY,
	},
	mutation::{
		COMMENT_CREATE_MUTATION, ISSUE_ARCHIVE_MUTATION, ISSUE_CREATE_MUTATION,
		ISSUE_UPDATE_BRIEF_MUTATION, ISSUE_UPDATE_MUTATION,
	},
	team::TEAM_LABEL_BY_NAME_QUERY,
};

pub(super) const LINEAR_GRAPHQL_URL: &str = "https://api.linear.app/graphql";
