mod candidate_selection_allows_dispatch_when_another_issue_has_active_lease;
mod candidate_selection_blocks_ordinary_dispatch_for_retained_review_handoff_marker;
mod candidate_selection_breaks_ties_by_identifier_after_created_at;
mod candidate_selection_does_not_requery_queue_label_for_truncated_candidates;
mod candidate_selection_skips_todo_issue_with_nonterminal_blockers;
mod candidate_selection_sorts_by_priority_created_at_and_identifier;
