#!/usr/bin/env python3
"""Shared contract helpers for GitHub bundle and signal-entry tooling."""

from __future__ import annotations

from contract_support.basic import validate_analysis_draft, validate_bundle, validate_signal
from contract_support.constants import (
    ANALYSIS_MODES,
    BUNDLE_SCHEMA,
    CODEX_COMPATIBILITY_STATUSES,
    CODEX_TARGET_CHANNELS,
    CONTROL_PLANE_UPGRADE_CANDIDATE_SCHEMA,
    CONTROL_PLANE_UPGRADE_IMPACTS,
    CONTROL_PLANE_UPGRADE_PATHS,
    CONTROL_PLANE_UPGRADE_STATUSES,
    FLAG_RE,
    GENERIC_COMMIT_TITLES,
    ISSUE_REF_RE,
    RELEASE_DELTA_SCHEMA,
    SIGNAL_CONFIDENCE,
    SIGNAL_IMPACT,
    SIGNAL_KINDS,
    SIGNAL_SCHEMA,
    SOURCE_ITEM_KINDS,
    UPSTREAM_REVIEW_ACTION_TYPES,
    UPSTREAM_REVIEW_NEXT_STEPS,
    UPSTREAM_REVIEW_PRIORITIES,
    UPSTREAM_REVIEW_QUEUE_SCHEMA,
    UPSTREAM_REVIEW_SCHEMA,
    UPSTREAM_SOURCE_STATES,
    UPSTREAM_SUBJECT_KINDS,
)
from contract_support.control_plane import validate_control_plane_upgrade_candidate
from contract_support.core import (
    ValidationResult,
    collect_flags,
    collect_issue_refs,
    first_line,
    load_json,
    slugify,
    truncate_patch,
    utc_now_iso,
)
from contract_support.release import validate_release_delta
from contract_support.upstream import validate_upstream_review, validate_upstream_review_queue

__all__ = [
    "ANALYSIS_MODES",
    "BUNDLE_SCHEMA",
    "CODEX_COMPATIBILITY_STATUSES",
    "CODEX_TARGET_CHANNELS",
    "CONTROL_PLANE_UPGRADE_CANDIDATE_SCHEMA",
    "CONTROL_PLANE_UPGRADE_IMPACTS",
    "CONTROL_PLANE_UPGRADE_PATHS",
    "CONTROL_PLANE_UPGRADE_STATUSES",
    "FLAG_RE",
    "GENERIC_COMMIT_TITLES",
    "ISSUE_REF_RE",
    "RELEASE_DELTA_SCHEMA",
    "SIGNAL_CONFIDENCE",
    "SIGNAL_IMPACT",
    "SIGNAL_KINDS",
    "SIGNAL_SCHEMA",
    "SOURCE_ITEM_KINDS",
    "UPSTREAM_REVIEW_ACTION_TYPES",
    "UPSTREAM_REVIEW_NEXT_STEPS",
    "UPSTREAM_REVIEW_PRIORITIES",
    "UPSTREAM_REVIEW_QUEUE_SCHEMA",
    "UPSTREAM_REVIEW_SCHEMA",
    "UPSTREAM_SOURCE_STATES",
    "UPSTREAM_SUBJECT_KINDS",
    "ValidationResult",
    "collect_flags",
    "collect_issue_refs",
    "first_line",
    "load_json",
    "slugify",
    "truncate_patch",
    "utc_now_iso",
    "validate_analysis_draft",
    "validate_bundle",
    "validate_control_plane_upgrade_candidate",
    "validate_release_delta",
    "validate_signal",
    "validate_upstream_review",
    "validate_upstream_review_queue",
]
