mod before_remove_hook_does_not_run_for_unregistered_directory;
mod before_remove_hook_failure_blocks_cleanup;
mod before_remove_hook_runs_before_cleanup;
mod rejects_reused_non_worktree_checkout_with_embedded_git_dir;
mod rejects_worktree_removal_when_path_escapes_root_via_parent_components;
mod removes_linked_worktree_path;
mod removes_orphaned_marker_directory_without_linked_git_metadata;
mod removes_orphaned_run_control_marker_directory_without_linked_git_metadata;
