"""Lifecycle hook constants compatibility facade."""

from __future__ import annotations

from .hint_text import (
    ANTI_MONOLITH_HINT,
    COMMIT_COMMAND_TERMS,
    COMMIT_SCHEMA,
    COMMIT_STYLE_HINT,
    DELIBERATION_GATE_HINT,
    DEPENDENCY_POLICY_HINT,
    ENGLISH_ONLY_HINT,
    FAKE_MODULARIZATION_HINT,
    KNOWLEDGE_HINT,
    MODULE_BOUNDARY_HINT,
    PUBLIC_SURFACE_HINT,
    REPO_WORK_HINT,
    ROOT_TASK_BRANCH_BLOCK,
    ROOT_TASK_BRANCH_SWITCH_BLOCK,
    TASK_RUNNER_HINT,
)
from .shell_constants import (
    ALWAYS_MUTATING_TOOL_NAMES,
    GIT_BRANCH_CREATE_OPTIONS,
    GIT_GLOBAL_OPTIONS_WITH_ARG,
    GIT_GLOBAL_OPTIONS_WITH_VALUE_PREFIX,
    GIT_OPTIONS_WITH_ARG,
    MUTATING_COMMAND_TERMS,
    REDIRECTION_OPERATORS,
    SHELL_MUTATING_COMMANDS,
)
from .surface_constants import (
    DEPENDENCY_SURFACE_NAMES,
    EXCLUDED_LARGE_CHANGE_PARTS,
    FAKE_RUST_MODULARIZATION_PATTERNS,
    GENERIC_MODULE_BUCKET_SEGMENTS,
    LARGE_ADDITION_THRESHOLD,
    LARGE_CHANGE_THRESHOLD,
    LARGE_SOURCE_FILE_LINE_THRESHOLD,
    LARGE_SOURCE_TOUCH_THRESHOLD,
    MODULE_BOUNDARY_PROMPT_TERMS,
    NEW_SOURCE_FILE_THRESHOLD,
    PUBLIC_SURFACE_NAMES,
    PUBLIC_SURFACE_PREFIXES,
    PUBLIC_SURFACE_SEGMENTS,
    PUBLIC_SURFACE_STEMS,
    SOURCE_ADDITION_THRESHOLD,
    SOURCE_EXTENSIONS,
    STATE_DIR,
    STATE_PATH,
    TASK_RUNNER_NAMES,
)
