mod generated_schema_marker_validation_accepts_required_markers;
mod generated_schema_marker_validation_rejects_legacy_flat_dynamic_tools;
mod generated_schema_marker_validation_rejects_missing_markers;
mod generated_schema_marker_validation_rejects_missing_owned_method;
mod generated_schema_marker_validation_rejects_prose_only_markers;
mod matches_thread_id_from_supported_notification_shapes;
mod probe_result_shape_is_stable;
