mod late_protocol_events_after_archive_discard_are_restart_safe;
mod late_protocol_events_after_thread_archive_use_discarded_sequence_namespace;
mod post_archive_discard_append_rebuilds_stale_compacted_protocol_summary;
mod pre_archive_protocol_replays_remain_idempotent_after_archive;
mod protocol_event_replay_is_idempotent_when_payload_matches;
mod protocol_event_sequence_conflict_rejects_changed_payload;
mod sparse_protocol_event_replay_keeps_leased_run_summary_count_exact;
